### ISSUE TITLE
stargazer breaks completely after using statsmodels get_robustcov_results

### ISSUE THREAD

**Issue by randomgambit** [mwburke/stargazer#110]
Hi there and thanks for this package! I noticed stargazer breaks if I fit a OLS model with statsmodels and then I modify it using get_robustcov_results.

As this adjustment is pretty common in econometrics, is this something you can look at? 

Thanks

**Comment by toobaz** [comment]
Hi @randomgambit , sorry for the late reply.

Can you provide a MRE that "breaks completely"? The following seems to work fine:

```python
import pandas as pd
from sklearn import datasets
from statsmodels.api import OLS
from stargazer.stargazer import Stargazer

diabetes = datasets.load_diabetes()

df = pd.DataFrame(diabetes.data, columns=diabetes['feature_names'])
df['target'] = diabetes['target']

ols = OLS.from_formula('target ~ age + sex + bmi', data=df).fit()

table = Stargazer([ols.get_robustcov_results(), ols])

table
```

**Comment by toobaz** [comment]
Closing, please reopen if there's anything I missed.
