### ISSUE TITLE
No module named 'stargazer'

### ISSUE THREAD

**Issue by diogoalvesderesende** [mwburke/stargazer#17]
Hey everyone,

When I try to import by running:
`from stargazer.stargazer import Stargazer`
The following error appears:
```
from stargazer.stargazer import Stargazer

ModuleNotFoundError: No module named 'stargazer'
```

Could you help out?

Thanks!

**Comment by nightvision04** [comment]
Were you using a virtual environment to do the install? If so, perhaps you hadn't activated it prior to running `pip install stargazer`?

**Comment by diogoalvesderesende** [comment]
I was trying to run it on Spyder in my local machine. And I did install it in the command prompt. Don't know how to solve it. Can you help? Thank you!

**Comment by nightvision04** [comment]
Sure, I may be able to help. 

What's the explicit path that Spyder is using as your python executable? If you don't know that's what you'll need to find out next. I suspect that there are multiple python installations and/or environments on your machine and we will need to sort out which one Spyder is trying to use.

**Comment by toobaz** [comment]
Apparently not a bug, closing.
