### ISSUE TITLE
Number of Latex columns rendered fixed to two

### ISSUE THREAD

**Issue by brandonek15** [mwburke/stargazer#18]
I noticed the number of columns that is rendered in the latex code is fixed at two. I was able to fix it in a very simple manner.  See the before an after attached.

Thank you for creating this. This is super useful!
![before_after_stargazer](https://user-images.githubusercontent.com/33203937/78841801-fa1cda80-79c3-11ea-9851-e0da2668cc25.png)

**Comment by toobaz** [comment]
@brandonek15 any reason why you closed this? It seems a legitimate report and the solution also seems correct.

**Comment by brandonek15** [comment]
@toobaz I submitted a pull request with my code change, so I removed the report. I am pretty new to github so I wasn't sure the procedure for suggesting an edit. I originally posted the report and then later figured out how to submit a pull request.

Thanks!
