### ISSUE TITLE
Is there a way tou use pandas' dataframes as inputs?

### ISSUE THREAD

**Issue by lucascr91** [mwburke/stargazer#25]
In R, one can use dataframes as input in the function stargazer, then the output can be a statistical summary of variables (summary=TRUE) or just the plain dataframe (summary=FALSE).

It looks like this current implementation of stargazer in python only accepts regressions models as input

**Comment by toobaz** [comment]
Isn't the "statistical summary of variables" just provided by ``pd.DataFrame.describe()``?

**Comment by lucascr91** [comment]
Of course, but this doesn't generate an output in TEX format, I guess. The point is that the current module don't accept anything other than a regression object as input, while in R the user do have this option

**Comment by toobaz** [comment]
> Of course, but this doesn't generate an output in TEX format, I guess

``df.describe().to_latex()``

**Comment by lucascr91** [comment]
Sorry, I wasn't aware of this method. Thank you for the answer.

**Comment by toobaz** [comment]
No problem.
