### ISSUE TITLE
Remove decimal from observation count

### ISSUE THREAD

**Issue by MaxGhenis** [mwburke/stargazer#30]
From the [example notebook](https://github.com/mwburke/stargazer/blob/master/examples.ipynb) (also shows up in latex output):
![image](https://user-images.githubusercontent.com/6076111/83576369-7a544d80-a4e6-11ea-9b85-edc78549311f.png)

**Comment by MaxGhenis** [comment]
Looks like this would be fixed in https://github.com/mwburke/stargazer/pull/12. @csemken is anything more needed for that PR other than @mwburke's approval?

**Comment by toobaz** [comment]
Fixed by #21
