### ISSUE TITLE
F statistic sometimes has brackets around it

### ISSUE THREAD

**Issue by MaxGhenis** [mwburke/stargazer#33]
In some of my regression tables, the F statistic is printed as `[[value]]`, e.g.:
![image](https://user-images.githubusercontent.com/6076111/83590959-bea61480-a50b-11ea-97dc-5a2adbb14667.png)

In other very similar tables, it's shown without them, e.g.:
![image](https://user-images.githubusercontent.com/6076111/83591106-02008300-a50c-11ea-8abc-d77707531708.png)

The only difference between these sets of models is the set of regressors. I've removed stars and F-statistic degrees of freedom from both; see the [notebook](https://github.com/MaxGhenis/mit_1432/blob/ae3f879c1e46d0dde517d1449d6dd1ae360b4faa/p3_regressions.ipynb) for the full code. I couldn't figure out a more minimal example to reproduce the issue.

**Comment by toobaz** [comment]
Not sure what's causing this, and it's difficult to reproduce without the data. Did c492e65e3eb98746a38277a9878eb6e491e4d731 change anything? Does this happen also with ``render_latex``?

**Comment by toobaz** [comment]
Never mind, I was able to reproduce. Apparently, a ``RegressionResults.fvalue`` is a scalar by default but becomes a 2D ``numpy.array`` with (some?) robust standard errors.

**Comment by toobaz** [comment]
See https://github.com/statsmodels/statsmodels/issues/6778
