### ISSUE TITLE
Custom latex strings aren't passed correctly to latex output

### ISSUE THREAD

**Issue by MaxGhenis** [mwburke/stargazer#35]
e.g. `stargazer.custom_columns('\beta')` produces this latex ([notebook](https://colab.research.google.com/drive/1OQX3dEG39S1R4v9mcdsQTAZ3S6b65p5o#scrollTo=DTdXOHi6KXyZ)):
```
\\multicolumn{2}{c}{\x08eta}
```
It seems like this might be happening because it's first parsed as HTML?
![image](https://user-images.githubusercontent.com/6076111/83591813-afc06180-a50d-11ea-86f8-d3d2f1021967.png)

**Comment by toobaz** [comment]
> e.g. `stargazer.custom_columns('\beta')`

In this code, the backslash is never recorded as such, as ``\b`` is read as an escaped character, and stargazer can't do anything about it.

Try ``stargazer.custom_columns('\\beta')`` or ``stargazer.custom_columns(r'\beta')``.
