### ISSUE TITLE
Render_latex() string not formatted for .tex file

### ISSUE THREAD

**Issue by faurehu** [mwburke/stargazer#63]
When I run `stargazer.render_latex()` I get the following string:

```
'\\begin{table}[!htbp] \\centering\n\\begin{tabular}{@{\\extracolsep{5pt}}lccc}\n\\\\[-1.8ex]\\hline\n\\hline \\\\[-1.8ex]\n& \\multicolumn{3}{c}{\\textit{Dependent variable:}} \\\n\\cr \\cline{3-4}\n\\\\[-1.8ex] & \\multicolumn{1}{c}{Stickers} & \\multicolumn{1}{c}{Aggregators} & \\multicolumn{1}{c}{Hunters}  \\\\\n\\\\[-1.8ex] & (1) & (2) & (3) \\\\\n\\hline \\\\[-1.8ex]\n p_dist & -0.049$^{***}$ & -0.164$^{***}$ & 0.000$^{}$ \\\\\n  & (0.000) & (0.000) & (0.000) \\\\\n q_dist & -0.006$^{***}$ & 0.101$^{***}$ & -0.054$^{***}$ \\\\\n  & (0.000) & (0.000) & (0.000) \\\\\n\\hline \\\\[-1.8ex]\n Observations & 50 & 50 & 50 \\\\\n $R^2$ &  &  &  \\\\\n Adjusted $R^2$ &  &  &  \\\\\n Residual Std. Error & 1.000(df = 48) & 1.000(df = 48) & 1.000(df = 48)  \\\\\n F Statistic & $^{}$ (df = 1; 48) & $^{}$ (df = 1; 48) & $^{}$ (df = 1; 48) \\\\\n\\hline\n\\hline \\\\[-1.8ex]\n\\textit{Note:} & \\multicolumn{3}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\\\\n\\end{tabular}\n\\end{table}'
```

Which my LaTeX compiler is not happy with. Common errors I get are:

* ! Undefined control sequence.
    * It is solved when I replace `\\begin` with `\begin`.
* ! LaTeX Error: There's no line here to end.
   * Solved when I get rid of `\n` with a new line.
* ! Misplaced alignment tab character &.
    * Solved when replacing `&` with a tab.

I get many other errors but I haven't figured out how to solve them but it is evident that the string that is given by `render_latex()` is not meant to go directly into my `.tex` file. Where can I put it? Can I produce a string that can go directly into a `.tex` file?

I have tried: 

* Removing the quotes
* Inserting it in `$` and `$$` blocks

**Comment by toobaz** [comment]
> I get many other errors but I haven't figured out how to solve them but it is evident that the string that is given by `render_latex()` is not meant to go directly into my `.tex` file. Where can I put it? Can I produce a string that can go directly into a `.tex` file?

Have you tried to ``print()`` the string, or even better, to save it to file rather than copypasting it?

**Comment by faurehu** [comment]
@toobaz this worked! Thank you very much.

I was using jupyter so I was looking at the output without printing.
