### ISSUE TITLE
Allow to set custom spacing between coefficients

### ISSUE THREAD

**Issue by toobaz** [mwburke/stargazer#66]
From #65 .

I don't like the idea of inserting empty lines like R stargazer does, but I do think it should be easy to take an optional argument, e.g. ``row_space=.3`` which results in 

``\\[.3cm]`` after the standard error lines.

**Comment by toobaz** [comment]
@nikchha should be fixed: numbers are interpreted in "em" by default but one can also be explicit in measurement unit, as in 

``table.cov_spacing = '3cm'``

**Comment by nikchha** [comment]
Thank you for your work! That's great
