### ISSUE TITLE
\cline (column line) showing up under left-most columns

### ISSUE THREAD

**Issue by ijyliu** [mwburke/stargazer#74]
I'm getting some (possibly undesirable?) behavior with a column line showing up under two left-most models for latex output. Is this intentional? It doesn't seem particularly logical/good to have as a default to me. Is there a setting for this I'm missing? I briefly skimmed the code on this repo but didn't find anything.

Example:
![image](https://user-images.githubusercontent.com/67396209/118909890-a8968d00-b8f1-11eb-9cae-a77b4adb7bb5.png)

LaTeX
```
\begin{table}[!htbp] \centering
        \begin{tabular}{@{\extracolsep{5pt}}lccccc}
        \\[-1.8ex]\hline
        \hline \\[-1.8ex]
        &amp; \multicolumn{5}{c}{\textit{Life Expectancy at Birth (Years)}} \
        \cr \cline{5-6}
        \\[-1.8ex] &amp; (1) &amp; (2) &amp; (3) &amp; (4) &amp; (5) \\
        \hline \\[-1.8ex]
         GDP Share of Health Exp. &amp; 0.258$^{***}$ &amp; 0.184$^{***}$ &amp; -0.024$^{}$ &amp; 0.144$^{***}$ &amp; -0.020$^{}$ \\
          &amp; (0.023) &amp; (0.019) &amp; (0.031) &amp; (0.017) &amp; (0.030) \\
         Covariates &amp; None &amp; Econ Indicators &amp; Econ Indicators &amp; PCs &amp; PCs \\
         Fixed Effects &amp; No &amp; No &amp; Yes &amp; No &amp; Yes \\
        \hline \\[-1.8ex]
         Observations &amp; 1,799 &amp; 1,799 &amp; 1,799 &amp; 1,799 &amp; 1,799 \\
         $R^2$ &amp; 0.067 &amp; 0.553 &amp; 0.987 &amp; 0.467 &amp; 0.987 \\
         Adjusted $R^2$ &amp; 0.066 &amp; 0.549 &amp; 0.985 &amp; 0.467 &amp; 0.985 \\
         Residual Std. Error &amp; 0.967 &amp; 0.672 &amp; 0.122 &amp; 0.730 &amp; 0.123  \\
         F Statistic &amp; 128.396$^{***}$  &amp; 146.946$^{***}$  &amp; 772.041$^{***}$  &amp; 787.819$^{***}$  &amp; 384.737$^{***}$  \\
        \hline
        \hline \\[-1.8ex]
        \textit{Note:} &amp; \multicolumn{5}{r}{$^{*}$p$&lt;$0.1; $^{**}$p$&lt;$0.05; $^{***}$p$&lt;$0.01} \\
         &amp; \multicolumn{5}{r}\textit{All variables are standardized.} \\
        \end{tabular}
```

I can confirm that `cline` produces this behavior. Currently for my class projects using this I've just been using regex to strip the `\cline{<number range>}` from the the render_latex() output.

This package is extremely convenient and awesome, thanks.

**Comment by toobaz** [comment]
Thanks for raising this. That line was conceived as a sort of styling of the dependent variable label. But indeed it sucks as of now.

Also looking at what the original stargazer does, I guess I would rather prolong the line to all models than removing it. Do you agree? See for instance the tables at https://www.r-bloggers.com/2013/07/tailor-your-tables-with-stargazer-new-features-for-latex-and-text-output/
