### ISSUE TITLE
Add multi column

### ISSUE THREAD

**Issue by mehrdad19** [mwburke/stargazer#79]
Hello,

My column titles are a bit long and that makes the output table really wide. Is there a way to change the multi column in the header to accept two or more columns?

thanks

**Comment by toobaz** [comment]
Sorry, not sure I understand. Are you asking for two columns (of two different models) to share their title/header?

**Comment by mehrdad19** [comment]
I apologize for my mistake. I see the header of the latex output uses "multirow", with one row. Is it possible to change it so it gets two or more rows as input? When the column titles are long, this is usually helpful to keep the width of the table reasonable. I apologize again for my mistake.

**Comment by toobaz** [comment]
> I see the header of the latex output uses "multirow"

Do you mean "multicolumn"?

**Comment by ozak** [comment]
@hqs811 can you share your solution? Not being able to do that would really limit the usefulness of the package, at least for my use case.

**Comment by toobaz** [comment]
You have to play with ``Stargazer.custom_column``, as follows:

```python3
table = Stargazer([mod1, mod1, mod2])
table.custom_columns(['identical', 'different'], [2, 1])
```

**Comment by ozak** [comment]
Perfect! Thanks!
