### ISSUE TITLE
render_latex() not working properly

### ISSUE THREAD

**Issue by achinmay17** [mwburke/stargazer#81]
Hi, 

Thanks for the amazing work! 

I am trying to use render_latex() command and its outputing a string instead of a table which looks like the attached screenshot? Am I missing something very obvious? I also tried print() and other known commands like %%latex in jupyter notebook, but they are also not rendering the latex. Please help. 

Thanks,

![image](https://user-images.githubusercontent.com/24596657/152100670-71c4d247-31a4-47f3-959e-0253012c06cc.png)

**Comment by toobaz** [comment]
``render_latex()`` produces code for inclusion in LaTeX documents. It is not meant to be rendered as an image. See https://github.com/mwburke/stargazer/issues/15
