### ISSUE TITLE
Error: Unrecognized object type for AER ivreg objects when specifying namespace

### ISSUE THREAD

**Issue by cwalker4** [mwburke/stargazer#92]
Stargazer isn't working for ivreg objects when I specify the namespace in the function call for ivreg. The following code chunk returns `% Error: Unrecognized object type.` Is this a KP? Or am I doing something painfully stupid?

```
library(AER)
library(stargazer)

x <- rnorm(100, 0, 1)
y <- rnorm(100, 1, 1)
z <- rnorm(100, 2, 1)

fit <- AER::ivreg(y ~ x | z)
stargazer(fit, type="text")
```

But, the following works as expected:

```
library(AER)
library(stargazer)

x <- rnorm(100, 0, 1)
y <- rnorm(100, 1, 1)
z <- rnorm(100, 2, 1)

fit <- ivreg(y ~ x | z)
stargazer(fit, type="text")

```

My sessionInfo for debugging:

```
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.6

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] stargazer_5.2.3 AER_1.2-10      survival_3.3-1  sandwich_3.0-2  lmtest_0.9-40   zoo_1.8-11     
[7] car_3.1-0       carData_3.0-5  

loaded via a namespace (and not attached):
[1] compiler_4.2.1  Matrix_1.5-1    tools_4.2.1     abind_1.4-5     splines_4.2.1   grid_4.2.1     
[7] Formula_1.2-4   lattice_0.20-45

```

**Comment by toobaz** [comment]
> Stargazer isn't working for ivreg objects when I specify the namespace in the function call for ivreg. The following code chunk returns `% Error: Unrecognized object type.` Is this a KP? Or am I doing something painfully stupid?

While "painfully stupid" would be widely exaggerated, please notice that this is the repo for the Python version of stargazer 😉️ I suspect the official way to report bugs to the R stargazer is writing a mail to mhlavac [at] alumni.princeton.edu. (from the package documentation).
