### ISSUE TITLE
Can I add names for subcolumns?

### ISSUE THREAD

**Issue by Hansyvea** [mwburke/stargazer#95]
for example: 
model 1      model 2
 -----------    ...
      B(SE)     OR
        1.2      2.3
      (0.03)

While show Standard Error only in one column instead of both of them

**Comment by toobaz** [comment]
Sorry, I'm not sure I understand.

If the question is "can I set column names", sure.

If the question is "can I only show Standard Error for one column", no.

**Comment by Hansyvea** [comment]
sorry for my bad writing. I have checked your post about setting column names. Using code like 
`table.custom_columns(['identical', 'different'], [2, 1])`, you have two sub-columns under 'identical', and my question is that can you give names to the sub-columns as well.

**Comment by toobaz** [comment]
OK, I understand now.

I just pushed a commit allowing to introduce custom lines in table header (it was already possible in body and footer). You can find an example in https://github.com/mwburke/stargazer/blob/master/examples.ipynb (see "`Add custom lines`").

This should allow you to do what you desire.
